In [7]:
from src.utils import get_user_info, get_root_path

In [8]:
user_info = get_user_info()
attributes = user_info.iloc[:, 52:146]

target = attributes.loc[:, attributes.columns.str.endswith('_no')]
target.to_csv(get_root_path() / 'data/interim/attributes.csv')
target.head()

,charming_no,cheerful_no,confident_no,contemporary_no,cool_no,corporate_no,daring_no,different_no,distinctive_no,downToEarth_no,...,successful_no,technical_no,tough_no,trendy_no,unique_no,upToDate_no,upperClass_no,western_no,wholesome_no,young_no
0,4,3,3,4,3,2,2,5,4,2,...,3,4,3,2,2,3,2,2,4,3
1,3,3,3,3,4,3,3,4,3,2,...,4,2,2,3,4,3,2,4,4,4
2,3,4,4,2,3,2,3,4,2,4,...,4,4,3,3,4,2,3,2,2,2
3,5,5,4,4,4,2,3,3,5,4,...,5,4,1,5,5,4,5,5,4,4
4,5,4,5,5,4,5,5,5,5,5,...,5,1,2,5,5,5,3,5,5,4